apiVersion: v1
kind: Service
metadata:
  name: {{ include "pikdame.name" . }}
  labels:
    {{- include "pikdame.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pikdame.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
