#!/usr/bin/env node
/**
 * Generates the parts of the documentation that must never drift from the code.
 *
 * Sphinx' autodoc is a PYTHON tool - it cannot read JavaScript. So instead of
 * pretending, this script extracts the hard facts straight from the source and
 * writes them as Markdown into docs/_generated/. Those files are committed (so
 * Read the Docs needs no Node at build time) and verified in CI: if someone
 * changes a constant, an env var or a protocol message without regenerating,
 * `npm run docs:check` fails.
 *
 *   node scripts/gen-docs.js          # write docs/_generated/*.md
 *   node scripts/gen-docs.js --check  # fail if the committed files are stale
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'docs', '_generated');
const BANNER = '<!-- GENERATED by scripts/gen-docs.js - do not edit by hand. Run `npm run docs:gen`. -->\n\n';

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* ---------------------------------------------------------------- env vars */
// Human-readable notes; the NAME, DEFAULT and USED-IN columns come from the code.
const ENV_NOTES = {
  PORT: 'HTTP/WebSocket port the server listens on.',
  PIKDAME_DATA_DIR: 'Directory for all persistent data (profiles, stats, accounts, session snapshot). Point this at your mounted volume.',
  PIKDAME_MAX_SESSIONS: 'Maximum number of concurrent games. Beyond it, new games are rejected with "server full".',
  PIKDAME_PUBLIC_MODE: 'Set to `1` on a public server: no player profiles are persisted and the lobby shows no player list. Anonymous global stats are still counted.',
  PIKDAME_ACCOUNTS: 'Set to `0` to disable user accounts entirely (pure guest play).',
  PIKDAME_DATABASE_URL: 'PostgreSQL connection string for accounts. If unset, a local SQLite file (`users.db`) inside the data directory is used.',
  PIKDAME_DATABASE_PASSWORD: 'Password for the PostgreSQL connection (also readable from a `_FILE` secret; see Configuration).',
  PIKDAME_BASE_URL: 'Public base URL used to build invite links and QR codes (e.g. `https://play.example.com`).',
  PIKDAME_ALLOWED_ORIGIN: 'If set, only WebSocket connections from this origin are accepted (CSRF hardening).',
  PIKDAME_TRUST_PROXY: 'Set to `1` when running behind a reverse proxy so client IPs are read from `X-Forwarded-For`.',
  PIKDAME_HEARTBEAT_MS: 'WebSocket ping interval used to detect dead connections.',
  PIKDAME_ONNX: 'Set to `1` to activate a trained ONNX bot policy (falls back to the heuristic bot if unavailable). See {doc}`onnx`.',
  PIKDAME_MODELS_DIR: 'Where the `.onnx` model files live. Override it to mount models on a volume and swap them without rebuilding the image. Default: the `models/` folder in the image.',
  PIKDAME_LOG_GAMES: 'Set to `1` to log human moves to JSONL for imitation learning.',
  PIKDAME_LOG_PATH: 'Where the move log is written.',
};

function generateConfiguration() {
  const files = ['server.js', ...fs.readdirSync(path.join(ROOT, 'game')).filter((f) => f.endsWith('.js')).map((f) => `game/${f}`)];
  const found = new Map(); // name -> { default, files:Set }

  for (const file of files) {
    const src = read(file);
    // `Number(process.env.X) || 30000` — the wrapper hides the default from the
    // plain pattern below, so handle it first.
    const reNum = /Number\(process\.env\.([A-Z_][A-Z0-9_]*)\)\s*\|\|\s*([0-9_]+)/g;
    let m;
    while ((m = reNum.exec(src)) !== null) {
      const entry = found.get(m[1]) || { default: '', files: new Set() };
      entry.default = `\`${m[2]}\``;
      entry.files.add(file);
      found.set(m[1], entry);
    }
    // `process.env.X || path.join(a, b, 'c')` - the generic pattern below would
    // truncate at the first comma, so capture the whole call first.
    const reJoin = /process\.env\.([A-Z_][A-Z0-9_]*)\s*\|\|\s*path\.join\(([^)]*)\)/g;
    while ((m = reJoin.exec(src)) !== null) {
      const inner = m[2];
      let def;
      if (inner.includes("'models'")) def = '`models/` inside the image';
      else if (inner.includes("'data'")) def = '`<app>/data`';
      else def = '_(path relative to the app)_';
      const entry = found.get(m[1]) || { default: '', files: new Set() };
      entry.default = def;
      entry.files.add(file);
      found.set(m[1], entry);
    }
    const re = /process\.env\.([A-Z_][A-Z0-9_]*)\s*(?:\|\|\s*([^;,)\n]+?))?\s*(?:[;,)\n]|===)/g;
    while ((m = re.exec(src)) !== null) {
      const name = m[1];
      let def = (m[2] || '').trim();
      // Tidy up the extracted default expression
      if (def.startsWith('path.join')) {
        // The joined path tells us what it actually defaults to.
        if (def.includes("'models'")) def = '`models/` in the image';
        else if (def.includes("'data'")) def = '`<app>/data`';
        else def = '_(a path relative to the app)_';
      }
      else if (def.startsWith('`http://$')) def = 'the request\'s own host';
      else if (def === 'null') def = 'unset';
      else if (def) def = `\`${def.replace(/`/g, '')}\``;
      const entry = found.get(name) || { default: '', files: new Set() };
      if (def && !entry.default) entry.default = def;
      entry.files.add(file);
      found.set(name, entry);
    }
    // `=== '1'` style flags have no || default
    const reFlag = /process\.env\.([A-Z_][A-Z0-9_]*)\s*===\s*'([^']+)'/g;
    while ((m = reFlag.exec(src)) !== null) {
      const entry = found.get(m[1]) || { default: '', files: new Set() };
      if (!entry.default) entry.default = `unset (compare against \`${m[2]}\`)`;
      entry.files.add(file);
      found.set(m[1], entry);
    }
  }
  // Vars only referenced indirectly (docker-compose / secrets helper)
  for (const extra of ['PIKDAME_DATABASE_URL', 'PIKDAME_DATABASE_PASSWORD']) {
    if (!found.has(extra)) found.set(extra, { default: 'unset', files: new Set(['game/AccountStore.js']) });
  }

  const rows = [...found.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, e]) => {
      const note = ENV_NOTES[name] || '_(undocumented - see source)_';
      return `| \`${name}\` | ${e.default || '—'} | ${note} |`;
    });

  return `${BANNER}# Environment variables

All settings are environment variables - there is no config file. This table is
generated from the source, so it cannot go stale.

| Variable | Default | Meaning |
| --- | --- | --- |
${rows.join('\n')}

:::{note}
Secrets can also be supplied via a \`*_FILE\` variable pointing at a file (Docker
secrets), e.g. \`PIKDAME_DATABASE_PASSWORD_FILE=/run/secrets/db_password\`.
:::
`;
}

/* ------------------------------------------------------- websocket protocol */
const MSG_NOTES = {
  createSession: 'Create a new game and receive its code.',
  joinSession: 'Join an existing game by code.',
  checkSession: 'Ask whether a stored session still exists (used by the "resume" button).',
  setName: 'Set or change the display name.',
  ready: 'Toggle lobby readiness.',
  startGame: 'Host only: start the game (empty seats are filled with bots).',
  setMaxSeats: 'Host only: change the number of seats (2-4).',
  reorderSeats: 'Host only: change the seating order.',
  setDealer: 'Host only: choose the dealer.',
  setBotDifficulty: 'Host only: set a bot seat\'s difficulty.',
  setHouseRules: 'Host only: change house rules (turn timer, "hand aus" doubling, strict threshold).',
  drawFromPile: 'Draw the top card of the face-down draw pile.',
  drawFromDiscard: 'Take the discard pile. Only allowed if its top card immediately forms a new combination - it must then be laid this turn.',
  layoutMeld: 'Lay out a new set or run.',
  layOff: 'Add a single card to one of your own melds.',
  layOffMulti: 'Add several cards to one of your own melds in one go.',
  swapJoker: 'Swap a joker on the table for the card it represents (the joker leaves play permanently).',
  discard: 'Discard exactly one card and end your turn.',
  forfeitRound: 'Vote to forfeit the whole game. The match only ends once every connected player agrees.',
  undoPileTake: 'Take back a discard-pile pickup - only while the mandatory top card has not been played yet (phase 1 of the two-phase pickup). Fair by construction: the card was public anyway and nothing on the table changed.',
  performCut: 'Interactive round start: the cutter picks where to cut the freshly shuffled deck (position 0..1). Only valid in the cutting phase, only for the cutter; bots, the daily challenge and timeouts cut automatically. The next state carries `lastCutReveal` (the lucky cards kept plus the ordinary card that ended the run) for the reveal animation.',
  togglePause: 'Vote to pause. The game only pauses once every connected player agrees.',
  nextRound: 'Signal readiness for the next round.',
  rematch: 'Start a new match with the same table.',
  emote: 'Send an emoji reaction to the table.',
  exportLastGame: 'Download the last finished game as JSON.',
  submitChallenge: 'Submit a daily-challenge score.',
  login: 'Log in to an account.',
  register: 'Create an account.',
  logout: 'Log out.',
};

function generateProtocol() {
  const src = read('server.js');
  const types = [...new Set([...src.matchAll(/case\s+'([a-zA-Z]+)'\s*:/g)].map((m) => m[1]))].sort();
  const rows = types.map((t) => `| \`${t}\` | ${MSG_NOTES[t] || '_(see source)_'} |`);

  return `${BANNER}# WebSocket protocol

The client talks to the server over a single WebSocket. Every message is JSON
with a \`type\` field. The list below is generated from the server's message
handler, so it always matches the running code.

## Client → server

| \`type\` | Purpose |
| --- | --- |
${rows.join('\n')}

## Server → client

| \`type\` | Purpose |
| --- | --- |
| \`state\` | The full game state as that player may see it (their own hand, everyone else's card counts). Sent after every change. |
| \`sessionCreated\` / \`sessionJoined\` | Confirms a game was created/joined; carries the code and the player's id. |
| \`sessionStatus\` | Answer to \`checkSession\`. |
| \`error\` | Something was rejected (with a human-readable reason). |
| \`emote\` | Someone (or a bot) sent a reaction. |
| \`jokerChoice\` | The move is ambiguous (a joker could stand for several cards); the client must pick one of the offered options. |
| \`gameExport\` | The requested game export (JSON). |

:::{note}
The server is the single source of truth: it validates every move and never
trusts client-supplied fields. The state a player receives never contains
another player's hand.
:::
`;
}

/* ---------------------------------------------------------- game constants */
function generateGameConstants() {
  const Deck = require(path.join(ROOT, 'game', 'Deck'));
  const ScoreBoard = require(path.join(ROOT, 'game', 'ScoreBoard'));
  const Rules = require(path.join(ROOT, 'game', 'Rules'));
  const { cardValue, makeStandardCard, makeJoker } = require(path.join(ROOT, 'game', 'Card'));

  const deck = Deck.createDeck();
  const jokers = deck.filter((c) => c.isJoker).length;

  const v = (suit, rank) => cardValue(makeStandardCard(suit, rank, 0));
  const values = [
    ['Queen of Spades (Pik Dame)', v('S', 'Q')],
    ['Joker', cardValue(makeJoker(0))],
    ['Ace', v('H', 'A')],
    ['10, Jack, Queen, King', v('H', '10')],
    ['2 - 9', v('H', '5')],
  ];

  const hr = ScoreBoard.DEFAULT_HOUSE_RULES;

  return `${BANNER}# Game constants

Generated from the game engine, so the numbers here are exactly the ones the
server plays with.

## Deck and deal

| | |
| --- | --- |
| Cards in play | **${deck.length}** (2 standard decks + jokers) |
| Jokers | **${jokers}** |
| Cards dealt per player | **${Deck.HAND_SIZE}** |
| Players | **2 - 4** |

## Card values

| Card | Points |
| --- | --- |
${values.map(([n, p]) => `| ${n} | **${p}** |`).join('\n')}

## Combinations

| | |
| --- | --- |
| Set (same rank) | ${3} - **${Rules.MAX_SET_SIZE}** cards, each suit at most **${Rules.MAX_PER_SUIT_IN_SET}×** (two decks) |
| Run (same suit) | ${3} - **13** cards, circular: \`K-A-2\` is valid, no rank twice |

## Scoring

| | |
| --- | --- |
| Game ends at | **${ScoreBoard.GAME_END_THRESHOLD}** points |
| \`handAusDoubles\` (default) | \`${hr.handAusDoubles}\` - going out in one turn doubles the round score |
| \`strictThreshold\` (default) | \`${hr.strictThreshold}\` - if true the game ends only *above* ${ScoreBoard.GAME_END_THRESHOLD}, not *at* it |

The winner of a round scores only their melds. Everyone else scores
*melds minus the cards left in hand* - so a Queen of Spades caught in hand costs
**${v('S', 'Q')}** points.
`;
}

/* ---------------------------------------------------------------------- run */
const outputs = {
  'configuration.md': generateConfiguration(),
  'protocol.md': generateProtocol(),
  'game-constants.md': generateGameConstants(),
};

const check = process.argv.includes('--check');
fs.mkdirSync(OUT_DIR, { recursive: true });

let stale = [];
for (const [name, content] of Object.entries(outputs)) {
  const file = path.join(OUT_DIR, name);
  if (check) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (current !== content) stale.push(name);
  } else {
    fs.writeFileSync(file, content, 'utf8');
    console.log(`wrote docs/_generated/${name}`);
  }
}

if (check) {
  if (stale.length) {
    console.error(`\nGenerated docs are STALE: ${stale.join(', ')}`);
    console.error('The code changed but the generated docs were not updated.');
    console.error('Run:  npm run docs:gen   and commit the result.\n');
    process.exit(1);
  }
  console.log('Generated docs are up to date.');
}
