"""Sphinx configuration for the Pik Dame documentation.

Docs are written in MARKDOWN (via MyST), not reStructuredText - the rest of the
project uses Markdown, so this keeps one format everywhere.

Note on "generating docs from the code": Sphinx' autodoc is a Python tool and
cannot read JavaScript. The parts that must never drift from the code (env
vars, WebSocket protocol, game constants) are therefore generated by
`scripts/gen-docs.js` into `docs/_generated/` and included here. CI fails if
they are stale (`npm run docs:check`).
"""

import json
import pathlib

# -- Project ----------------------------------------------------------------

project = "Pik Dame"
author = "Florian Deutsch"
copyright = "2026, Florian Deutsch"

# Single source of truth for the version: package.json
_pkg = json.loads((pathlib.Path(__file__).parent.parent / "package.json").read_text())
version = _pkg["version"]
release = version

# -- General ----------------------------------------------------------------

extensions = [
    "myst_parser",         # Markdown
    "sphinx_copybutton",   # copy button on code blocks
    "sphinx_design",       # cards/grids on the landing page
]

myst_enable_extensions = [
    "colon_fence",     # ::: fenced directives
    "deflist",
    "linkify",         # bare URLs become links
    "substitution",
    "tasklist",
]
myst_heading_anchors = 3  # auto anchors for h1-h3

source_suffix = {".md": "markdown"}
master_doc = "index"
# The generated fragments are INCLUDED into real pages and must not also be
# picked up as standalone documents.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "_generated/*",
    ".venv",
]

# -- HTML -------------------------------------------------------------------

html_theme = "furo"
html_title = f"Pik Dame {version}"
html_static_path = []  # no static assets; an empty dir does not survive Git
html_theme_options = {
    "source_repository": "https://github.com/floriandeutsch89/pikdame-local/",
    "source_branch": "main",
    "source_directory": "docs/",
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/floriandeutsch89/pikdame-local",
            "class": "",
            "html": (
                '<svg stroke="currentColor" fill="currentColor" viewBox="0 0 16 16">'
                '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
                "0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53."
                "63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 "
                "0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 "
                "2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 "
                "3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 "
                '8c0-4.42-3.58-8-8-8z"></path></svg>'
            ),
        },
    ],
}

# External links used across pages
extlinks = {}
